version: "3.7"
services:
  marquez_web:
    image: marquezproject/marquez-web:latest
    environment:
      - MARQUEZ_HOST=192.168.1.133
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - marquez

  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - MARQUEZ_CONFIG=/usr/src/app/marquez.yml
      - POSTGRES_HOST=192.168.1.133
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=buendia
      - POSTGRES_PASSWORD=macondo
    volumes:
      - ./docker/wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - ./docker/marquez.yml:/usr/src/app/marquez.yml
    entrypoint: ["./wait-for-it.sh", "192.168.1.133:5432", "--", "./entrypoint.sh"]
